name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
  - name: Setup JFrog CLI
  # You may pin to the exact commit or the version.
  # uses: jfrog/setup-jfrog-cli@128e747d1ab49209bace59204fee2ddb98fd05b1
  uses: jfrog/setup-jfrog-cli@v2.3.0
  with:
    # JFrog CLI Version
    version: # optional, default is 2.14.0
    # Remote repository in Artifactory pointing to 'https://releases.jfrog.io/artifactory/jfrog-cli'. Use this parameter in case you don't have an Internet access.
    download-repository: # optional
    jf rt bp
    jf bs
