name: DockerImageCI-latest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Artifactory
      uses: docker/login-action@v1
      with:
        registry: satheeshart.jfrog.io
        username: ${{ secrets.ARTIFACTORY_USERNAME }}
        password: ${{ secrets.ARTIFACTORY_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
         push: true
         tags: |
            hts1-docker-local.jfrog.io/docker-test:${{ github.sha }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Setup JFrog CLI
      # You may pin to the exact commit or the version.
      # uses: jfrog/setup-jfrog-cli@128e747d1ab49209bace59204fee2ddb98fd05b1
      uses: jfrog/setup-jfrog-cli@v2.3.0
      env:
        JF_ENV_1: ${{ secrets.HARISH_CLI_GITHUB_ACTIONS_SAAS }}
        buildInfo.env.publisher.publishArtifacts: true
        buildInfo.env.publisher.publishBuildInfo: true
    - run: |
        JFROG_CLI_LOG_LEVEL=DEBUG
        echo "hts1-docker-local.jfrog.io/docker-test:${{ github.sha }}@${{ steps.docker_build.outputs.digest }}" > image-file-details
    - run: |
        jf rt bdc docker-local --image-file image-file-details
    - run: |     
        jf rt bp
    - run: |    
        jf bs --fail=false
    - run: |    
        echo "artifactory buil info gathering complete"
    - name: analyse with Xray
      run: |
        docker images
        jd docker scan hts1-docker-local.jfrog.io/docker-test:${{ github.sha }}
        jf rt bs --fail
