name: DockerImageCI-latest
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v1
      with:
         registry: hts2-docker-local.jfrog.io
         username: frogtester7
         password: ${{ secrets.ARTIFACTORY_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
         push: true
         tags: |
            hts2-docker-local.jfrog.io/docker-test:${{ github.sha }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v2
      with: 
         version: 2.16.2
      env:
        JF_ENV_1: ${{ secrets.HARISH_CLI_GITHUB_ACTIONS_SAAS }}
    - name: Run JFROG CLI
      run: |
        echo "hts2-docker-local.jfrog.io/docker-test:${{ github.sha }}@${{ steps.docker_build.outputs.digest }}" > image-file-details
        jf rt build-docker-create hts2-docker-local.jfrog.io --image-file image-file-details 
        jf rt bp
        jf bs --fail=false
        echo "artifactory buil info gathering complete"
    - name: analyse with Xray
      run: |
        docker images
        jd docker scan hts2-docker-local.jfrog.io/docker-local/docker-test:${{ github.sha }}
        jf rt bs --fail
