name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Setup JFrog CLI
      # You may pin to the exact commit or the version.
      # uses: jfrog/setup-jfrog-cli@128e747d1ab49209bace59204fee2ddb98fd05b1
      uses: jfrog/setup-jfrog-cli@v2.3.0
      env:
        JF_ENV_1: ${{ secrets.HARISH_CLI_GITHUB_ACTIONS_SAAS }}
        buildInfo.env.publisher.publishArtifacts: true
        buildInfo.env.publisher.publishBuildInfo: true
    - run: |
        jf rt bp
        jf rt bs --fail
        
